common/models/Session.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "sessions".
 *
 * @property integer $id
 * @property integer $event_id
 * @property string $date
 * @property string $name
 * @property string $description
 * @property string $text
 * @property string $audio
 * @property string $text_file
 * @property string $video_url
 * @property string $video_code
 * @property integer $private
 * @property integer $state
 * @property string $created
 * @property string $edited
 * @property integer $creator
 * @property integer $editor
 */
class Session extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sessions';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['event_id', 'date', 'name'], 'required'],
            [['event_id', 'private', 'state', 'creator', 'editor'], 'integer'],
            [['date', 'created', 'edited'], 'safe'],
            [['description', 'text', 'video_code'], 'string'],
            [['name', 'audio', 'text_file', 'video_url'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'event_id' => 'Event ID',
            'date' => 'Date',
            'name' => 'Name',
            'description' => 'Description',
            'text' => 'Text',
            'audio' => 'Audio',
            'text_file' => 'Text file',
            'video_url' => 'Video URL',
            'video_code' => 'Video Code',
            'private' => 'Private',
            'state' => 'State',
            'created' => 'Created',
            'edited' => 'Edited',
            'creator' => 'Creator',
            'editor' => 'Editor',
        ];
    }

    public function getEvent()
    {
        return $this->hasOne(\common\models\Event::className(), ['id' => 'event_id']);
    }

    public function getTags()
    {
        return $this->hasMany(\common\models\Tag::className(), ['id' => 'tag_id'])
            ->viaTable('sessions_has_tags', ['session_id' => 'id']);
    }

    public function setTags($tags)
    {
        SessionsHasTags::deleteAll(['session_id' => $this->id]);
        $values = [];

        foreach ($tags as $tag_id) {
            $values[] = [$this->id, $tag_id];
        }

        self::getDb()->createCommand()
            ->batchInsert(SessionsHasTags::tableName(), ['session_id', 'tag_id'], $values)->execute();
    }
}

backend/controllers/EventController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Event;
use backend\models\EventSearch;
use common\models\Session;
use backend\models\SessionSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EventController implements the CRUD actions for Event model.
 */
class EventController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Event models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EventSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Event model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $searchSessionModel = new SessionSearch();
        $dataSessionProvider = $searchSessionModel->search(Yii::$app->request->queryParams);

        return $this->render('view', [
            'model' => $this->findModel($id),
            'searchSessionModel' => $searchSessionModel,
            'dataSessionProvider' => $dataSessionProvider,
        ]);
    }

    /**
     * Creates a new Event model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Event();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->created = date('Y-m-d H:i:s');
            $model->creator = Yii::$app->user->identity->getId();
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Event model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->edited = date('Y-m-d H:i:s');
            $model->editor = Yii::$app->user->identity->getId();
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Event model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Event model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Event the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Event::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/SessionController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Session;
use backend\models\SessionSearch;
use common\models\Event;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SessionController implements the CRUD actions for Session model.
 */
class SessionController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Session models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SessionSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Session model.
     * @param integer $id
     * @param integer $event_id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $event = Event::findOne(['id' => $model->event_id]);

        return $this->render('view', [
            'model' => $model,
            'event' => $event,
        ]);
    }

    /**
     * Creates a new Session model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @param integer $event_id
     * @return mixed
     */
    public function actionCreate($event_id)
    {
        $model = new Session();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->created = date('Y-m-d H:i:s');
            $model->creator = Yii::$app->user->identity->getId();
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            $event = Event::findOne(['id' => $event_id]);

            return $this->render('create', [
                'model' => $model,
                'event' => $event,
            ]);
        }
    }

    /**
     * Updates an existing Session model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        // Старые значения на случай если новые файлы не будут загружены
        $oldAudio = $model->audio;
        $oldTextFile = $model->text_file;

        if ($model->load(Yii::$app->request->post())) {
            // Загрузка аудио
            if ($audio = \yii\web\UploadedFile::getInstance($model, 'audio')) {
                $fileName = $audio->baseName . '.' . $audio->extension;
                $path = Yii::getAlias('@frontend/web/upload/audio/') . $fileName;
                $audio->saveAs($path);
                $model->audio = 'upload/audio/' . $fileName;
            } else {
                $model->audio = $oldAudio;
            }

            // Загрузка текстового файла
            if ($text_file = \yii\web\UploadedFile::getInstance($model, 'text_file')) {
                $fileName = $text_file->baseName . '.' . $text_file->extension;
                $path = Yii::getAlias('@frontend/web/upload/text/') . $fileName;
                $text_file->saveAs($path);
                $model->text_file = 'upload/text/' . $fileName;
            } else {
                $model->text_file = $oldTextFile;
            }

            // Если передана ссылка на youtube,
            // сгенерировать код iframe
            if ($model->video_url != '') {
                $pattern = '/http(s)?:\/\/(www\.)?(youtube\.com|youtu\.be)\/(watch\?[a-zA-Z0-9\&\-\_\=\%]*v\=)?([a-zA-Z0-9\-]+)(\&[a-zA-Z0-9\&\-\_\=\%\#]*)?/i';
                $frame = '<iframe width="560" height="315" src="//www.youtube.com/embed/$5" frameborder="0" allowfullscreen></iframe>';
                $model->video_code = preg_replace($pattern, $frame, $model->video_url);
            } else {
                $model->video_code = '';
            }

            // Теги
            $data = Yii::$app->request->post();
            $model->tags = $data['Session']['tags'];

            $model->edited = date('Y-m-d H:i:s');
            $model->editor = Yii::$app->user->identity->getId();
            $model->save();

            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            $event = Event::findOne(['id' => $model->event_id]);

            return $this->render('update', [
                'model' => $model,
                'event' => $event,
            ]);
        }
    }

    /**
     * Deletes an existing Session model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @param integer $event_id
     * @return mixed
     */
    public function actionDelete($id, $event_id)
    {
        $this->findModel($id, $event_id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Session model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Session the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Session::findOne(['id' => $id])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/session/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\bootstrap\ActiveForm;

use \common\models\Event;
use \common\models\Tag;

/* @var $this yii\web\View */
/* @var $model common\models\Session */
/* @var $model common\models\Tag */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="session-form">

    <?php $form = ActiveForm::begin([
        'options' => [
            'enctype' => 'multipart/form-data'
        ]
    ]); ?>

    <? /*=$form->field($model, 'event_id')->textInput()*/ ?>

    <?php
    $model->event_id = $event->id;
    ?>

    <?= $form->field($model, 'event_id')->dropDownList(ArrayHelper::map(Event::find()->all(), 'id', 'name'), [
        'readonly' => true,
        'value' => $event->id
    ]) ?>

    <?= $form->field($model, 'tags')->checkboxList(ArrayHelper::map(Tag::find()->all(), 'id', 'name'), [
        'options' => [
            1 => [
                'checked' => true,
            ]
        ]
    ]) ?>

    <?= $form->field($model, 'date')->textInput() ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'text')->textarea(['rows' => 6]) ?>

    <?= $model->audio ? $model->audio : '' ?>
    <?= $form->field($model, 'audio')->fileInput() ?>

    <?= $model->text_file ? $model->text_file : '' ?>
    <?= $form->field($model, 'text_file')->fileInput() ?>

    <?= $form->field($model, 'video_url')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'video_code')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'private')->checkbox() ?>

    <?= $form->field($model, 'state')->checkbox() ?>

    <?//= $form->field($model, 'created')->textInput() ?>

    <?//= $form->field($model, 'edited')->textInput() ?>

    <?//= $form->field($model, 'creator')->textInput() ?>

    <?//= $form->field($model, 'editor')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/session/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\SessionSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="session-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'event_id') ?>

    <?= $form->field($model, 'date') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'text') ?>

    <?php // echo $form->field($model, 'audio') ?>

    <?php // echo $form->field($model, 'video_url') ?>

    <?php // echo $form->field($model, 'video_code') ?>

    <?php // echo $form->field($model, 'private') ?>

    <?php // echo $form->field($model, 'state') ?>

    <?php // echo $form->field($model, 'created') ?>

    <?php // echo $form->field($model, 'edited') ?>

    <?php // echo $form->field($model, 'creator') ?>

    <?php // echo $form->field($model, 'editor') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/session/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Session */

$this->title = 'Create Session';
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['event/index']];
$this->params['breadcrumbs'][] = ['label' => $event->name, 'url' => ['event/view', 'id' => $event->id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="session-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Go to event', ['event/view/', 'id' => $event->id], ['class' => 'btn btn-success']) ?>
    </p>

    <?= $this->render('_form', [
        'model' => $model,
        'event' => $event,
    ]) ?>

</div>

backend/views/session/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\SessionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Sessions';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="session-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Session', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'event_id',
            'date',
            'name',
            'description:ntext',
            // 'text:ntext',
            // 'audio',
            // 'video_url:url',
            // 'video_code:ntext',
            // 'private',
            // 'state',
            // 'created',
            // 'edited',
            // 'creator',
            // 'editor',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

backend/views/session/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Session */

$this->title = 'Update Session: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['event/index']];
$this->params['breadcrumbs'][] = ['label' => $event->name, 'url' => ['event/view', 'id' => $event->id]];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id, 'event_id' => $model->event_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="session-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/session/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Session */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['event/index']];
$this->params['breadcrumbs'][] = ['label' => $event->name, 'url' => ['event/view', 'id' => $event->id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="session-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id, 'event_id' => $model->event_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id, 'event_id' => $model->event_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            // 'event_id',
            [
                'label' => 'Event',
                'value' => $model->event->name,
            ],
            [
                'label' => 'Teacher',
                'value' => $model->event->teacher->name,
            ],
            'date',
            'name',
            'description:ntext',
            'text:ntext',
            'audio',
            'text_file',
            'video_url:url',
            'video_code:ntext',
            // 'private',
            [
                'label' => 'Private',
                'value' => $model->private ? 'Yes' : 'No',
            ],
            // 'state',
            [
                'label' => 'State',
                'value' => $model->state ? 'Yes' : 'No',
            ],
            'created',
            'edited',
            'creator',
            'editor',
        ],
    ]) ?>

</div>